### ISSUE TITLE
[BUG]no response when clicking "list emails"

### ISSUE THREAD

**Issue by heywiorld** [emalderson/ThePhish#13]
**Describe the bug**

**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu   |
| OS version (client)        | 10        |
| Python version | 3|
| Type of email address used | company email, ... |
| Mail client type & version | O365 ... |
| Browser type & version     | Firefox  |
| Virtualized  Env.          | True / False                          |
| Dedicated RAM              | XX GB                                 |
| vCPU                       | 4          |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**To Reproduce**

1. Go to 'http://localhost:8080/'
2. Click on 'list emails'
3. But no response

**Expected behavior**

list emails.

**Screenshots**

**Additional context**

**Possible solutions**

seems some code is missing?

**Comment by emalderson** [comment]
Sorry for the delay in the response, but you didn't provide enough information to help me identify the possible cause of the problem. I'm pretty sure that there is a problem with your installation procedure.

**Comment by spexboy** [comment]
Hello Team,

When i am trying to fetch the email from my inbox, it showing "There are no e-mails to read".

![image](https://user-images.githubusercontent.com/13061021/163691913-17dd22d6-f7b6-4c21-9078-e10b7dfde36f.png)

Please find the logs below,

![image](https://user-images.githubusercontent.com/13061021/163691985-13af26f1-7289-4cde-b499-1a306dc1d66d.png)

Kindly help to find out the issue.

thank you.

**Comment by badspoiler** [comment]
Hello, i have a similar problem. When i click "list E-Mails" i get a "Error" Message and "an Error occured"
I installed everything like in the "Install ThePhish using Docker and Docker Compose" guide.

Where can i see logs for this error message? Thank you!
![error](https://user-images.githubusercontent.com/80466731/170715883-e2e90bb9-ed73-46c6-bf4c-fe3be521d009.png)

**Comment by emalderson** [comment]
Hi badspoiler, probably something went wrong during the installation process.
You can see detailed error by attaching to the logs on the "thephish" container and look at the stack trace of the error after you click on the button.

**Comment by Gokzkara** [comment]
Hello. 

I have the same problem and I get the following error from docker logs. Can anyone help?



thephish         | [ERROR]_[list_emails]: Error while trying to connect to IMAP server: Traceback (most recent call last):
thephish         |   File "/root/thephish/list_emails.py", line 243, in main
thephish         |     connection = connect_to_IMAP_server()
thephish         |   File "/root/thephish/list_emails.py", line 21, in connect_to_IMAP_server
thephish         |     connection.login(config['imapUser'], config['imapPassword'])
thephish         |   File "/usr/lib/python3.8/imaplib.py", line 601, in login
thephish         |     typ, dat = self._simple_command('LOGIN', user, self._quote(password))
thephish         |   File "/usr/lib/python3.8/imaplib.py", line 1205, in _simple_command
thephish         |     return self._command_complete(name, self._command(name, *args))
thephish         |   File "/usr/lib/python3.8/imaplib.py", line 1030, in _command_complete
thephish         |     raise self.error('%s command error: %s %s' % (name, typ, data))
thephish         | imaplib.IMAP4.error: LOGIN command error: BAD [b'Not enough arguments provided c12mb44063055ljj']

**Comment by emalderson** [comment]
This kind of problem is caused by wrong configuration of the parameters to connect to the email account.

**Comment by emalderson** [comment]
This kind of problem is caused by wrong configuration of the parameters to connect to the email account.

**Comment by gabyavra** [comment]
I have the same error, the credentials are fine
   "imap" : {
                "host" : "imap.gmail.com",
                "port" : "993",
                "user" : "email@gmail.com",
                "password" : "password",
                "folder" : "inbox"
        },


Error

thephish         | [ERROR]_[list_emails]: Error while trying to connect to IMAP server: Traceback (most recent call last):
thephish         |   File "/root/thephish/list_emails.py", line 243, in main
thephish         |     connection = connect_to_IMAP_server()
thephish         |   File "/root/thephish/list_emails.py", line 21, in connect_to_IMAP_server
thephish         |     connection.login(config['imapUser'], config['imapPassword'])
thephish         |   File "/usr/lib/python3.8/imaplib.py", line 601, in login
thephish         |     typ, dat = self._simple_command('LOGIN', user, self._quote(password))
thephish         |   File "/usr/lib/python3.8/imaplib.py", line 1205, in _simple_command
thephish         |     return self._command_complete(name, self._command(name, *args))
thephish         |   File "/usr/lib/python3.8/imaplib.py", line 1030, in _command_complete
thephish         |     raise self.error('%s command error: %s %s' % (name, typ, data))
thephish         | imaplib.IMAP4.error: LOGIN command error: BAD [b'Not enough arguments provided h10mb16417107edv']

**Comment by emalderson** [comment]
There is probably a problem with the parameters you used. Are you sure you used the correct credentials? Maybe you didn't use the app password for gmail, the standard password won't work.

**Comment by gabyavra** [comment]
It worked after I enabled 2FA  and used app password instead of normal password. Without 2FA and with normal pass didn't work. Strange.

**Comment by emalderson** [comment]
Yes, normal password will never work for apps. That's the reason why you need to use the app password.
