### ISSUE TITLE
[BUG] List emails not working

### ISSUE THREAD

**Issue by KaiJun-GP** [emalderson/ThePhish#19]
**Describe the bug**

ThePhish mentioned no e-mails to read, but mentioned that there are unread messages to process

**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Kali Linux   |
| OS version (client)        | Kali Linux           |
| Python version | |
| Type of email address used | Gmail |
| Mail client type & version | Gmail |
| Browser type & version     | Edge                   |
| Virtualized  Env.          | True                          |
| Dedicated RAM              | 6.5 GB                                 |
| vCPU                       | 4 / 8 / 16 / 32                       |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True  |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**To Reproduce**

**Expected behavior**

ThePhish should list the email

**Screenshots**

![image](https://user-images.githubusercontent.com/83260914/175284587-15ecfb6e-db99-4546-9d05-9656d7647b35.png)
![image](https://user-images.githubusercontent.com/83260914/175284629-c086b7e1-b38d-455a-a9bd-556373704d4b.png)

**Additional context**

I think I have enabled everything correct through the Docker method, but ThePhish is still unable to list emails.
I also ensured to forward as attachment to "thephishanalyzer@gmail.com", but still unable to list emails

**Possible solutions**

Keep this section if you have suggestions on how to solve the problem, otherwise delete it.

**Comment by emalderson** [comment]
I think you're sending emails to thephishanalyzer@gmail.com, which is MY email address used to test the tool. You should be using YOUR OWN email address...
![image](https://user-images.githubusercontent.com/49370319/175817323-b919952b-76e0-48cd-b933-42dbae95907b.png)

**Comment by KaiJun-GP** [comment]
I see, I misread the instructions I thought we have to forward the emails to a specific email

**Comment by emalderson** [comment]
No worries, I hope it'll work now!

**Comment by KaiJun-GP** [comment]
Yup it is working now. Thanks!
