### ISSUE TITLE
[Question] How can we update the container version?

### ISSUE THREAD

**Issue by fatmeat** [emalderson/ThePhish#21]
**Question**

Hello, first of all thank you for the amazing tools, I'm using docker installation method and had fun for last few days, wanted to know if there is a way to update the docker like theHive/Cortex/MISP's version without losing all the configuration?

Thank you again!

**Comment by emalderson** [comment]
Hi, you can just change the container versions in the `docker-compose.yml` file. For example, you can write `:latest` instead of `:<version_number>` for TheHive, Cortex and MISP. However, I can't assure you that everything will 100% work since I've never tested ThePhish with those newer versions.

**Comment by ivan-mai** [comment]
Thank you, I will let you know the results, I'm asking this because of I want to update the Cortex's analyzer!

**Comment by asterictnl-lvdw** [comment]
Do you have an update about if it works? I want to test it as well to see if it works or not.

**Comment by emalderson** [comment]
Windows is not officially supported at the moment.
