### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by zax400** [emalderson/ThePhish#24]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian   |
| OS version (client)        | Debian       |
| Python version | |
| Type of email address used | outlook|
| Mail client type & version | outlook|
| Browser type & version     | Firefox                |
| Virtualized  Env.          | True                    |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       |  8                      |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True / False |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**Question**
Error in cases
[ERROR]_[run_analysis]: Error while trying to notify the start of analysis: Traceback (most recent call last):
thephish         |   File "/usr/local/lib/python3.8/dist-packages/cortex4py/api.py", line 106, in do_post
thephish         |     response.raise_for_status()
thephish         |   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 953, in raise_for_status
thephish         |     raise HTTPError(http_error_msg, response=self)
thephish         | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://cortex:9001/api/responder/_search?range=0-1
thephish         | 
thephish         | The above exception was the direct cause of the following exception:
thephish         | 
thephish         | Traceback (most recent call last):
thephish         |   File "/root/thephish/run_analysis.py", line 568, in main
thephish         |     notify_start_of_analysis(case, task_ids['Notification'], mail_to, wsl)
thephish         |   File "/root/thephish/run_analysis.py", line 55, in notify_start_of_analysis
thephish         |     mailer_responder = api_cortex.responders.get_by_name('Mailer_1_0')
thephish         |   File "/usr/local/lib/python3.8/dist-packages/cortex4py/controllers/responders.py", line 22, in get_by_name
thephish         |     return self._wrap(self._find_one_by(Eq('name', name)), Responder)
thephish         |   File "/usr/local/lib/python3.8/dist-packages/cortex4py/controllers/abstract.py", line 29, in _find_one_by
thephish         |     collection = self._api.do_post(url, {'query': query or {}}, params).json()
thephish         |   File "/usr/local/lib/python3.8/dist-packages/cortex4py/api.py", line 109, in do_post
thephish         |     self.__recover(ex)
thephish         |   File "/usr/local/lib/python3.8/dist-packages/cortex4py/api.py", line 46, in __recover
thephish         |     raise AuthenticationError("Authentication error") from exception
thephish         | cortex4py.exceptions.AuthenticationError: Authentication error
thephish         | 
cassandra        | INFO  [Service Thread] 2022-08-02 15:15:47,309 GCInspector.java:285 - ConcurrentMarkSweep GC in 430ms.  CMS Old Gen: 49304 -> 65512; Par Eden Space: 858980352 -> 51411816; Par Survivor Space: 43551056 -> 0
thehive          | [info] o.t.t.s.IntegrityCheckActor [|] End of CaseTemplate global check: Map(orphans -> 0, duration -> 24)

**Comment by emalderson** [comment]
Hello, I read about some sort of authentication error in the logs. My best guess here is that you've configured the interaction between TheHive and Cortex in the wrong way. Try to review the tokens that you used to connect the two components.
