### ISSUE TITLE
Automatic running analyze after new email was arrived.

### ISSUE THREAD

**Issue by majo053** [emalderson/ThePhish#28]
**Question**

Is there any way to run automatic analyze after new email was arrived?

Thank you.

Majo

**Comment by scatenag** [comment]
:+1:

**Comment by emalderson** [comment]
Unfortunately this is not what ThePhish is about. You can maybe edit the code to just analyze unread emails in batch, but you need to trigger the analysis manually. You may also force it to actively polling for unread emails every X minutes and then start the analysis on one or more of them.
