### ISSUE TITLE
[Question] How to troubleshoot "Error while trying to notify the start of analysis"

### ISSUE THREAD

**Issue by mclancy10006** [emalderson/ThePhish#3]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian 11..   |
| Python version |3.9 |
| Type of email address used | Gmail |
| Mail client type & version | gmail|
| Browser type & version     | Edge                   |
| Virtualized  Env.          | True                       |
| Dedicated RAM              |  16 GB                                 |
| vCPU                       | 4 / 8   |
| ThePhish version  |           |
| TheHive version  |       4.1.11-1    |
| Cortex version  |     3.1.1-1      |
| MISP version  |       2.4    |
| Installed using Docker and Docker Compose |  False |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**Question**

Describe the question/requirement as clearly as possible.
Can't figure out how to get past this error when emailing a notification status.  The analysis part runs, but then get stuck here.

[INFO]_[case_from_email]: Added observable file Payment Confirmation Invoice no#333339.eml to case 18
[ERROR]_[run_analysis]: Error while trying to notify the start of analysis: Traceback (most recent call last):
  File "/home/xxxxx/ThePhish/app/run_analysis.py", line 573, in main
KeyError: 'Notification'

[ERROR]_[run_analysis]: Error while trying to notify the start of analysis: Traceback (most recent call last):
  File "/home/xxxxx/ThePhish/app/run_analysis.py", line 573, in main
KeyError: 'Notification'

**Comment by emalderson** [comment]
The problem has been fixed in the documentation, closed.
