### ISSUE TITLE
[BUG] Error while trying to connect to IMAP server

### ISSUE THREAD

**Issue by gru3zi** [emalderson/ThePhish#32]
**Describe the bug**

After setting it up all up and despite using a virtual environment I still am unable to get the gmail authentication to work. I have tried two different app passwords with gmail resulting in the same issue. 

**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu  |
| OS version (client)        | 20.04.5 LTS   |
| Python version | 3.8.10 |
| Type of email address used | Gmail |
| Mail client type & version | Gmail |
| Browser type & version     | Chrome         |
| Virtualized  Env.          | True                      |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 6                       |
| ThePhish version  |    Where do I find this info? latest git clone       |
| TheHive version  |     5.0.18-1      |
| Cortex version  |   cortex0 - 3.1.7-1  |
| MISP version  |      MISP - 2.4.164     |
| Installed using Docker and Docker Compose | False |

![image](https://user-images.githubusercontent.com/44057919/215282298-79147037-dbb5-4829-a28a-d1f5ff5b9064.png)

**To Reproduce**

1. Go to the Phish URL'
2. Click on List emails'
4. An error is produced

**Expected behavior**

Expect a valid connection to gmail 

**Screenshots**

Dependencies met

![image](https://user-images.githubusercontent.com/44057919/215279761-3a5cf093-31d0-4b7f-88f6-ef0473af01a6.png)

App password configured 

![image](https://user-images.githubusercontent.com/44057919/215282413-abfa05ef-aa81-45cc-8aa6-c4bb9e1310fe.png)

Config file 

![image](https://user-images.githubusercontent.com/44057919/215279844-b0b40a33-f94c-4e43-92d3-4f946b72113d.png)

![image](https://user-images.githubusercontent.com/44057919/215279894-2b727830-16d9-49b7-af80-788855d2e5ec.png)

Error 

![image](https://user-images.githubusercontent.com/44057919/215281922-aa40e14f-d15b-4451-bc9f-c5f37ad6df0b.png)

![image](https://user-images.githubusercontent.com/44057919/215281946-60b309de-f37c-43a7-91ae-5b6c37a71876.png)

**Additional context**

My Hive, Cortex and MISP is hosted on another container within my proxmox server. 

The only thing I cant seem to get working is the "Add the run_responder()". Is it still relevant for my case? Do I run the command on my ThePhish container or my other container holding thehive?

**Comment by emalderson** [comment]
I see from your environment that you're using TheHive 5. ThePhish has not been tested on TheHive 5. This is the reason why your "add_run_responder()" will never work.
However, this issue seems to be unrelated to TheHive or ThePhish itself, it is likely more of a configuration problem either in your configuration file or with your Google App password.
I suggest you switch to TheHive 4 to try ThePhis, maybe you can use the docker-compose available in the repo.

**Comment by gabyavra** [comment]
I have the same error, the credentials are fine
"imap" : {
"host" : "imap.gmail.com",
"port" : "993",
"user" : "[email@gmail.com](mailto:email@gmail.com)",
"password" : "password",
"folder" : "inbox"
},

Error

thephish | [ERROR]_[list_emails]: Error while trying to connect to IMAP server: Traceback (most recent call last):
thephish | File "/root/thephish/list_emails.py", line 243, in main
thephish | connection = connect_to_IMAP_server()
thephish | File "/root/thephish/list_emails.py", line 21, in connect_to_IMAP_server
thephish | connection.login(config['imapUser'], config['imapPassword'])
thephish | File "/usr/lib/python3.8/imaplib.py", line 601, in login
thephish | typ, dat = self._simple_command('LOGIN', user, self._quote(password))
thephish | File "/usr/lib/python3.8/imaplib.py", line 1205, in _simple_command
thephish | return self._command_complete(name, self._command(name, *args))
thephish | File "/usr/lib/python3.8/imaplib.py", line 1030, in _command_complete
thephish | raise self.error('%s command error: %s %s' % (name, typ, data))
thephish | imaplib.IMAP4.error: LOGIN command error: BAD [b'Not enough arguments provided h10mb16417107edv']


Any advice? Thank you.
