### ISSUE TITLE
[ERROR]: Error while trying to create the case

### ISSUE THREAD

**Issue by r1c4rd0r0ch4** [emalderson/ThePhish#33]
Hi,

After click open "Analyze" button, some messages shows up and suddenly it appears a message saying: [ERROR]: Error while trying to create the case.

How can I debug that?

Any idea?

**Comment by r1c4rd0r0ch4** [comment]
https://iili.io/H1kWPLX.png

**Comment by emalderson** [comment]
Are you using a version of TheHive that is supported by ThePhish? Also, have you set the API keys correctly? It seems like the API request is not being fulfilled.

**Comment by r1c4rd0r0ch4** [comment]
Hi, the issue has been solved. API key wasn´t correct!
Thank you so much!
