### ISSUE TITLE
[Question]CaseTemplate not found

### ISSUE THREAD

**Issue by gentlexue** [emalderson/ThePhish#38]
I came across this error, can you tell what template should I set for thehive?
[ERROR]: Cannot create template: 404 ({"type":"NotFoundError","message":"CaseTemplate not found"})

**Comment by emalderson** [comment]
Hi, the case template is called "ThePhish" and its creation and use is automated by the application, you don't have to set it explicitly. The error that you are facing looks more like a problem with the API itself that is used to create the case template.
