### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by hackdoors** [emalderson/ThePhish#40]
i login in success，but recieving mails has error，the error show this：

could u tell me how i fix it？i will thanks very much！

<img width="1578" alt="image" src="https://github.com/emalderson/ThePhish/assets/48487393/91d71417-a6e1-4deb-9e4b-d74ece4575be">

**Comment by zain0456** [comment]
have u found any way to fix this error?

**Comment by emalderson** [comment]
Hello. Unfortunately, errors like these need a thorough testing process. Those are infact related to the absurdly big number of ways in which an email can be encoded into the MIME multipart format. I managed to cover the most widespread use cases, but I cannot predict how every email client encodes the emails. This means that the fields that ThePhish needs to extract are not located in any of the fields that I search in programmatically, so the code breaks. Plus, there may also be some issues with chinese or japanese characters.
