### ISSUE TITLE
How to change the email message that thephish sends.

### ISSUE THREAD

**Issue by xekhz** [emalderson/ThePhish#41]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian, Ubuntu, CentOS, RedHat, ...   |
| OS version (client)        | XP, Seven, 10, Ubuntu, ...            |
| Python version | |
| Type of email address used | Gmail, Hotmail, ... |
| Mail client type & version | Thunderbird, Gmail, ... |
| Browser type & version     | Firefox, Chrome, Edge, Opera, ...                    |
| Virtualized  Env.          | True / False                          |
| Dedicated RAM              | XX GB                                 |
| vCPU                       | 4 / 8 / 16 / 32                       |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True / False |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**Question**

Describe the question/requirement as clearly as possible.

**Comment by emalderson** [comment]
Hello, ThePhish automatically creates a case template if it does not exist for the first time, then continues to use it for every new case. You can either change the default descriptions in the `run_analysis.py` file, or change the description of the first and third tasks of the case template manually from TheHive once it has been created for the first time.
