### ISSUE TITLE
Ciao non riesco nell'installazione [Question]

### ISSUE THREAD

**Issue by giangiluca** [emalderson/ThePhish#43]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu server 22.03  macchina virtuale con 16 gb ram 2 cpu e 250 di disco|

Nell'installazione ricevo questo errore
potresti aiutarmi?

Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
elasticsearch    | output:
elasticsearch    | [0.000s][error][logging] Error opening log file 'logs/gc.log': Permission denied
elasticsearch    | [0.000s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
elasticsearch    | error:
elasticsearch    | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
elasticsearch    | Error: Could not create the Java Virtual Machine.
elasticsearch    | Error: A fatal exception has occurred. Program will exit.
elasticsearch    |      at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
elasticsearch    |      at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
elasticsearch    |      at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
elasticsearch    |      at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
elasticsearch    |      at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
elasticsearch exited with code 1

**Question**

Describe the question/requirement as clearly as possible.

**Comment by emalderson** [comment]
Ciao, prova a seguire quanto scritto al punto 3 qui: https://github.com/emalderson/ThePhish/tree/master/docker#run-the-containers-with-docker-compose

Dovrebbe essere un problema di permessi, stoppa i container, prova a dare i permessi e a riavviarli, anche più volte se necessario, finché non funziona. Ciò è causato dal fatto che i files vengono creati in un secondo momento e non hanno i permessi del tuo utente, quindi devi darglieli in seguito alla loro creazione.
