### ISSUE TITLE
[BUG] - Crowdsec_Analyzer_1_0: Job AobGi4wB0KV4xh-jmuSh has be updated (JsDefined("Failure"))

### ISSUE THREAD

**Issue by figueiredosandro666** [emalderson/ThePhish#44]
When running Crowdsec Analyzer against an IP address, Cortex always fails:

cortex           | [info] c.s.d.c.LoggingPullHandler - pull docker.io/cortexneurons/crowdsec_analyzer:1: ProgressMessage{id=1, status=Pulling from cortexneurons/crowdsec_analyzer, stream=null, error=null, progress=null, progressDetail=null}
cortex           | [info] c.s.d.c.LoggingPullHandler - pull docker.io/cortexneurons/crowdsec_analyzer:1: ProgressMessage{id=null, status=Digest: sha256:d99a82be3ef69a823d14db0ed34bed1151a028f968f9b4a87aef6e27984b268c, stream=null, error=null, progress=null, progressDetail=null}
cortex           | [info] c.s.d.c.LoggingPullHandler - pull docker.io/cortexneurons/crowdsec_analyzer:1: ProgressMessage{id=null, status=Status: Image is up to date for cortexneurons/crowdsec_analyzer:1, stream=null, error=null, progress=null, progressDetail=null}
cortex           | [info] o.t.c.s.DockerJobRunnerSrv - Execute container 41c6783a56caec06399fd0167b3fc15a15a211739141b68502f3f005505d6d67
cortex           |   timeout: 30 minutes
cortex           |   image  : docker.io/cortexneurons/crowdsec_analyzer:1
cortex           |   volume : /tmp/cortex-jobs/cortex-job-AobGi4wB0KV4xh-jmuSh-239385392839758287:/job
cortex           | [info] c.s.d.c.DefaultDockerClient - Starting container with Id: 41c6783a56caec06399fd0167b3fc15a15a211739141b68502f3f005505d6d67
cortex           | [info] o.t.c.s.AuditActor - Job AobGi4wB0KV4xh-jmuSh has be updated (JsDefined("Failure"))
cortex           | [info] o.t.c.s.JobSrv - Job AobGi4wB0KV4xh-jmuSh has finished with status Failure

Looking into the message on Cortex web interface, a Python exception is shown:

Traceback (most recent call last):
  File "/worker/Crowdsec/crowdsec_analyzer.py", line 4, in <module>
    from crowdsec_api import Crowdsec
  File "/worker/Crowdsec/crowdsec_api.py", line 2, in <module>
    from requests.compat import urljoin
ModuleNotFoundError: No module named 'requests'

I tried to install "requests" on the cortex container, but I then realized that the neurons run on their own containers....

Thanks for any help

**Comment by emalderson** [comment]
Hello, I think this is a problem with that specific neuron. I don't own the code of the neurons, so you should not use it for now. Just disable that neuron.
