### ISSUE TITLE
There are no e-mails to read

### ISSUE THREAD

**Issue by giangiluca** [emalderson/ThePhish#45]
Hi, I installed the system on Windows configured and it seems to work without errors. The thing I can't understand is why when I launch it it tells me emails are not present when in relation to the logs I see that it downloads them. can you help me?

**Comment by emalderson** [comment]
First of all, I have never tested it on Windows. Anyway, this is likely a problem with your email and IMAP configuration. With no additional info I cannot help you more than this.

**Comment by giangiluca** [comment]
Thanks for the reply I also installed the system in linux ubuntu from the logs I see that it queries the email inbox and finds the emails but in the gui it tells me emails are not present

**Comment by emalderson** [comment]
Can you provide such logs?

**Comment by giangiluca** [comment]
![Webpage](https://github.com/emalderson/ThePhish/assets/31504114/c0e757a0-1c54-4de9-82b7-8af084169756)
![Log](https://github.com/emalderson/ThePhish/assets/31504114/4e4bed4b-ca19-4f90-b2e4-4b881bda14a1)

**Comment by giangiluca** [comment]
here it is

**Comment by giangiluca** [comment]
sorry resolved i don't attach email

**Comment by Razichennouf** [comment]
Hello @giangiluca i'm having the same issue could you please elaborate on your latest answer ?

**Comment by gopithangam** [comment]
I am also getting same error. Can some help to resolve this isuses?

**Comment by emalderson** [comment]
This happens when you don't set the IMAP information correctly, or when you don't forward the email in the right way.
