### ISSUE TITLE
[ERROR]: Error during the analysis task - Why does this happen?

### ISSUE THREAD

**Issue by figueiredosandro666** [emalderson/ThePhish#46]
The error happens during the analysis, ThePhish GUI displays the error message, and the analysis stops.

Looking into the logs, we can see this message:

[error] o.t.t.c.c.s.CortexActor [|] CortexActor received job output OutputJob(7Rsx1IwB-UJszOBmP3Bj,f8f874decbb877a41361ee9c94feb746,TorProject_1_0,TorProject_1_0,Thu Jan 04 11:17:26 UTC 2024,Some(Thu Jan 04 11:17:26 UTC 2024),Some(Thu Jan 04 11:18:12 UTC 2024),Success,Some(XXX.XXX.XXX.XXX),None,CIB1,ip,Some(OutputReport(Vector(OutputMinireport(info,TorProject,Node,false)),Some({}),true,Vector(),Vector(),None,None)),analyzer) but did not have it in state List()

XXX.XXX.XXX.XXX is a valid IPv4 address. I just changed it for privacy issues.

Before that error message, there is another one:

thephish         | [INFO]_[run_analysis]: Started analyzer TorProject_1_0 for ip XXX.XXX.XXX.XXX
thephish         | [ERROR]_[run_analysis]: Error during the analysis task: Traceback (most recent call last):
thephish         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
thephish         |     httplib_response = self._make_request(
thephish         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
thephish         |     six.raise_from(e, None)
thephish         |   File "<string>", line 3, in raise_from
thephish         |   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
thephish         |     httplib_response = conn.getresponse()
thephish         |   File "/usr/lib/python3.8/http/client.py", line 1344, in getresponse
thephish         |     response.begin()
thephish         |   File "/usr/lib/python3.8/http/client.py", line 307, in begin
thephish         |     version, status, reason = self._read_status()
thephish         |   File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
thephish         |     raise RemoteDisconnected("Remote end closed connection without"
thephish         | http.client.RemoteDisconnected: Remote end closed connection without response

Again, XXX.XXX.XXX.XXX is a valid IPv4 address.

I'll disable this analyzer and see if it works smoothly.

Best regards and a happy new year!!

**Comment by emalderson** [comment]
Hello, this may be a problem with that specific analyzer. Try disabling it and see if it works.
