### ISSUE TITLE
Issue regarding configuration

### ISSUE THREAD

**Issue by kunalhiremath** [emalderson/ThePhish#50]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        |  Ubuntu,   |
| OS version (client)        | Ubuntu 22  |
| Python version | |
| Type of email address used | Gmail |
| Mail client type & version | Gmail |
| Browser type & version     | Firefox   |
| Virtualized  Env.          | True            |
| Dedicated RAM              | 8 GB       |
| vCPU                       | 8 |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True |

**Question**

When accessing ThePhish web interface, I am trying to click the TheHive link from left menu but it is not opening( I am getting the message "Trouble finding the site"). below is my configuration file:

{
        "imap" : {
                "host" : "imap.gmail.com",
                "port" : "993",
                "user" : "***************@gmail.com",
                "password" : "*****************",
                "folder" : "inbox"
        },
        "thehive" : {
                "url" : "http://thehive:9000",
                "apikey" : "gLFo6Dz+g805UxbEwvWdimW"
        },
        "cortex" : {
                "url" : "http://cortex:9001",
                "apikey" : "ZuNzKNKRVa8YE6zf2l7YJsUwL",
                "id" : "local"
        },
        "misp" : {
                "id" : "MISP THP"
        },
        "case" : {
                "tlp" : "2",
                "pap" : "2",
                "tags" : ["email", "ThePhish"]
        }
}
~

**Comment by stavoxnetworks** [comment]
Same issue with me running the docker container version. No aspects of the site outside of the main page are accessible.

**Comment by kunalhiremath** [comment]
@stavoxnetworks By running the above command did it fix the issue.
