### ISSUE TITLE
Come è possibiole modificare la pagina iniziale e le risposte dell'email

### ISSUE THREAD

**Issue by skyluke70** [emalderson/ThePhish#52]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian, Ubuntu, CentOS, RedHat, ...   |
| OS version (client)        | XP, Seven, 10, Ubuntu, ...            |
| Python version | |
| Type of email address used | Gmail, Hotmail, ... |
| Mail client type & version | Thunderbird, Gmail, ... |
| Browser type & version     | Firefox, Chrome, Edge, Opera, ...                    |
| Virtualized  Env.          | True / False                          |
| Dedicated RAM              | XX GB                                 |
| vCPU                       | 4 / 8 / 16 / 32                       |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True / False |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**Question**

Ciao ho installato tutto sotto ubuntu ma non riesco a capire come si può personalizzare la pagina iniziale di thephish sono andato sotto la directory app/template e ho apportato le modifiche riavviando tutto anche il sistema continua a non prenderle e anche modificando il file run_analysis.py per personalizzare le risposte non cambia nulla cosa dovrei fare per far si che le modifiche abbiano effetto?
grazie

**Comment by emalderson** [comment]
Ciao, se hai modificato i files nelle cartelle static e templates all'interno del container ThePhish, prova a riavviare il container usando il comando restart di docker. Se hai già provato, potrebbe essere un problema di caching del tuo browser.

**Comment by skyluke70** [comment]
Grazie per la risposta ma ieri ho trovato la soluzione: quello che si trova all'esterno del docker anche se modificato come index.html non ha effetto perché il docker è stato preparato con quella base quindi anche se modifichi diciamo tutto quello che hai nell' directory App non va. Bisogna fare partire il docker e lavorare dentro il docker e farlo ripartire ma mai dare il comando con build che riporterebbe tutto all'origine perdendo le modifiche. Complimenti bel progetto sarebbe interessante una guida per l'installazione da zero.

**Comment by emalderson** [comment]
Sì esatto, l'immagine rimane sempre la stessa, sarà poi il container quello su cui poi vai a scrivere. Se rimuovi il container perdi tutto ciò che hai scritto su di esso, riportandoti all'immagine base. Il mio consiglio è quello di usare i comandi stop, start e restart di docker, che non distruggono il container, preservando le modifiche. Le uniche cose che puoi modificare da fuori sono quelle mappate nei volumi, quindi ad esempio i files di configurazione.

Per l'installazione da zero purtroppo è un po' più complesso, in quanto i tool sottostanti non sono sviluppati da me e potrebbero presentare cambiamenti con le versioni successive, per questo ho fissato le versioni che funzionano di sicuro nel docker compose.
