### ISSUE TITLE
[Bug] Attachments (txt) are not parsed

### ISSUE THREAD

**Issue by ClaudioWayne** [emalderson/ThePhish#9]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu 20.04.03 |
| OS version (client)        | Ubuntu 20.04.03            |
| Python version |Python 3.8.10 |
| Type of email address used | Gmail |
| Mail client type & version | Thunderbird |
| Browser type & version     | Firefox                    |
| Virtualized  Env.          | True                         |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 2                       |
| ThePhish version  |      recent     |
| TheHive version  |   4.1.11-1        |
| Cortex version  |     3.1.1-1       |
| MISP version  |    not used       |
| Installed using Docker and Docker Compose | False |
| Docker Version | If applicable |
| Docker Compose version | If applicable |

**Question**

Hi,
first of all thank you for developing this tool.

### A) - Attachments are not parsed
My Problem is that Attachments of an E-Mail are not parsed.
This is what i do:
1. Want to analyze this Mail with invoice.txt attached
![Bug2_LI](https://user-images.githubusercontent.com/35531629/139226522-4e3a7341-e7c5-4592-b15d-9589660f3628.jpg)

2. Forward mail via Thunderbird to ThePish Gmail-Account
![Bug3_LI](https://user-images.githubusercontent.com/35531629/139226961-9dd4c81b-24b8-4f0b-97b8-2879624d1e06.jpg)

3. Start ThePhish Analysis

4. invoice.txt is not listed in observable and not analyzed
![Bug5_LI](https://user-images.githubusercontent.com/35531629/139227666-6091dabb-41c3-4a04-9310-68f8afe15fe1.jpg)

5. If i download the mail in TheHive (ziped) invoice.txt is still attached to the mail so it seems that the mail is received correctly by ThePhish but invoice.txt is not recolonized.

![Bug6_LI](https://user-images.githubusercontent.com/35531629/139229683-f055ae69-dba5-4815-871c-818e91f00841.jpg)
.txt is not whitelisted.

Am i missing something here? Can you help me out? 

### B) - html-tags for hyperlinks gets recolonized as part of the URL
Moreover some html-tags for hyperlinks gets recolonized as part of the URL as u can see here:
![bug7](https://user-images.githubusercontent.com/35531629/139229226-6b92f8b4-1f04-4e3a-a156-d69628d9f598.png)

### C) - mini report from the URL-Haus Analyzer is not shown in observables
Independent from the ThePhish i recognized another little issue, maybe u have a solution for that or you can give me hint how to debug this:
The mini report from the URL-Haus Analyzer is not shown in observables
![bug9](https://user-images.githubusercontent.com/35531629/139230033-afe84404-fc1f-42ca-b766-4ebdf2124722.png)
 But it has hits 
![bug8_LI](https://user-images.githubusercontent.com/35531629/139230644-2defd863-345d-49bd-a3f7-10274a920a0f.jpg)

Do you have any idea how to fix that?

Thank you!

Claudio

**Comment by emalderson** [comment]
Bug fixed with the latest commit.
